compile:
	javac *.java Part1.java

run:
	java Part1

javadoc:
	javadoc *.java Part1.java -d part1javadoc

crun: compile run

clean:
	rm DynamicGraph.class
	rm Edge.class
	rm Graph.class
	rm MyGraph.class
	rm Part1.class
	rm Vertex.class